<template>
    <div>
        <v-card>
        <v-card-item>
          <v-card-text>
            <p style="font-weight: 700; font-size: x-large;" class="my-5">Defensive Buildings
                <button @click="toggleTableVisibility">
                    <v-icon v-if="showDefensiveBuildingsTable" icon="mdi mdi-menu-up"></v-icon>
                    <v-icon v-else icon="mdi mdi-menu-down"></v-icon>
                </button>
            </p>
            <v-card-text v-if="showDefensiveBuildingsTable">
                <p style="font-size: large; font-style: italic;">
                    Total time until the Defensive Buildings are completely upgraded: 
                    <span style="font-weight: 700;">
                        {{ getTimer() }}
                    </span>
                </p>
                <div @updateTotalTime="updateTotalTime"></div>
            </v-card-text>
            <v-lazy>
                <v-table v-if="showDefensiveBuildingsTable">
                  <thead>
                    <tr>
                      <th class="text-left" style="font-weight: 700; color: #000;">Name</th>
                      <th class="text-left" style="font-weight: 700; color: #000;">Seconds</th>
                      <th class="text-left" style="font-weight: 700; color: #000;">Minutes</th>
                      <th class="text-left" style="font-weight: 700; color: #000;">Hours</th>
                      <th class="text-left" style="font-weight: 700; color: #000;">Days</th>
                      <th class="text-left" style="font-weight: 700; color: #000;">Price</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr v-for="defensiveBuilding in currentDefensiveBuildings" :key="defensiveBuilding.name">
                        <td>{{ defensiveBuilding.name }}</td>
                        <td>{{ defensiveBuilding.seconds }}</td>
                        <td>{{ defensiveBuilding.minutes }}</td>
                        <td>{{ defensiveBuilding.hours }}</td>
                        <td>{{ defensiveBuilding.days }}</td>
                        <td>{{ defensiveBuilding.price }}</td>
                    </tr>
                  </tbody>
                </v-table>
            </v-lazy>
          </v-card-text>
        </v-card-item>
      </v-card>
    </div>
</template>

<script>
    export default {
        props: {
            THLevelMenu: String,
            THLevels: Array,
        },
    data() {
    return {
      showDefensiveBuildingsTable: false,
      DefensiveBuildings: {
            THLVL1: [
            {
                name: 'Cannon (Build)',
                seconds: 10,
                minutes: 0,
                hours: 0,
                days: 0,
                price: "250 Gold",
            },
            {
                name: 'Cannon (Build)',
                seconds: 10,
                minutes: 0,
                hours: 0,
                days: 0,
                price: "250 Gold",
            },
            {
                name: 'Cannon Level 2',
                seconds: 0,
                minutes: 2,
                hours: 0,
                days: 0,
                price: "1,000 Gold",
            },
            {
                name: 'Cannon Level 2',
                seconds: 0,
                minutes: 2,
                hours: 0,
                days: 0,
                price: "1,000 Gold",
            },
            ],
            THLVL2: [
            {
                name: 'Cannon Level 3',
                seconds: 0,
                minutes: 10,
                hours: 0,
                days: 0,
                price: "4,000 Gold",
            },
            {
                name: 'Cannon Level 3',
                seconds: 0,
                minutes: 10,
                hours: 0,
                days: 0,
                price: "4,000 Gold",
            },
            {
                name: 'Archer Tower (Build)',
                seconds: 0,
                minutes: 1,
                hours: 0,
                days: 0,
                price: "1,000 Gold",
            },  
            {
                name: 'Archer Tower Level 2',
                seconds: 0,
                minutes: 15,
                hours: 0,
                days: 0,
                price: "2,000 Gold",
            },  
            ],
            THLVL3: [
            {
                name: 'Cannon Level 4',
                seconds: 0,
                minutes: 45,
                hours: 0,
                days: 0,
                price: "16,000 Gold",
            },
            {
                name: 'Cannon Level 4',
                seconds: 0,
                minutes: 45,
                hours: 0,
                days: 0,
                price: "16,000 Gold",
            },
            {
                name: 'Archer Tower Level 3',
                seconds: 0,
                minutes: 45,
                hours: 0,
                days: 0,
                price: "5,000 Gold",
            },  
            {
                name: 'Mortar (Build)',
                seconds: 0,
                minutes: 0,
                hours: 3,
                days: 0,
                price: "5,000 Gold",
            },
            ],
            THLVL4: [
            {
                name: 'Cannon Level 5',
                seconds: 0,
                minutes: 0,
                hours: 2,
                days: 0,
                price: "16,000 Gold",
            },
            {
                name: 'Cannon Level 5',
                seconds: 0,
                minutes: 0,
                hours: 2,
                days: 0,
                price: "16,000 Gold",
            },
            {
                name: 'Archer Tower (Build)',
                seconds: 0,
                minutes: 1,
                hours: 0,
                days: 0,
                price: "1,000 Gold",
            },  
            {
                name: 'Archer Tower Level 2',
                seconds: 0,
                minutes: 15,
                hours: 0,
                days: 0,
                price: "2,000 Gold",
            }, 
            {
                name: 'Archer Tower Level 3',
                seconds: 0,
                minutes: 45,
                hours: 0,
                days: 0,
                price: "5,000 Gold",
            },  
            {
                name: 'Archer Tower Level 4',
                seconds: 0,
                minutes: 0,
                hours: 3,
                days: 0,
                price: "20,000 Gold",
            },  
            {
                name: 'Archer Tower Level 4',
                seconds: 0,
                minutes: 0,
                hours: 3,
                days: 0,
                price: "20,000 Gold",
            },  
            {
                name: 'Mortar Level 2',
                seconds: 0,
                minutes: 0,
                hours: 6,
                days: 0,
                price: "25,000 Gold",
            },
            {
                name: 'Air Defense (Build)',
                seconds: 0,
                minutes: 0,
                hours: 3,
                days: 0,
                price: "22,000 Gold",
            },
            {
                name: 'Air Defense Level 2',
                seconds: 0,
                minutes: 0,
                hours: 12,
                days: 0,
                price: "90,000 Gold",
            },
            ],
            THLVL5: [
            {
                name: 'Cannon (Build)',
                seconds: 10,
                minutes: 0,
                hours: 0,
                days: 0,
                price: "250 Gold",
            },
            {
                name: 'Cannon Level 2',
                seconds: 0,
                minutes: 2,
                hours: 0,
                days: 0,
                price: "1,000 Gold",
            },
            {
                name: 'Cannon Level 3',
                seconds: 0,
                minutes: 10,
                hours: 0,
                days: 0,
                price: "4,000 Gold",
            },
            {
                name: 'Cannon Level 4',
                seconds: 0,
                minutes: 45,
                hours: 0,
                days: 0,
                price: "16,000 Gold",
            },
            {
                name: 'Cannon Level 5',
                seconds: 0,
                minutes: 0,
                hours: 2,
                days: 0,
                price: "16,000 Gold",
            },
            {
                name: 'Cannon Level 6',
                seconds: 0,
                minutes: 0,
                hours: 4,
                days: 0,
                price: "100,000 Gold",
            },
            {
                name: 'Cannon Level 6',
                seconds: 0,
                minutes: 0,
                hours: 4,
                days: 0,
                price: "100,000 Gold",
            },
            {
                name: 'Cannon Level 6',
                seconds: 0,
                minutes: 0,
                hours: 4,
                days: 0,
                price: "100,000 Gold",
            },
            {
                name: 'Archer Tower (Build)',
                seconds: 0,
                minutes: 1,
                hours: 0,
                days: 0,
                price: "1,000 Gold",
            },  
            {
                name: 'Archer Tower Level 2',
                seconds: 0,
                minutes: 15,
                hours: 0,
                days: 0,
                price: "2,000 Gold",
            }, 
            {
                name: 'Archer Tower Level 3',
                seconds: 0,
                minutes: 45,
                hours: 0,
                days: 0,
                price: "5,000 Gold",
            }, 
            {
                name: 'Archer Tower Level 4',
                seconds: 0,
                minutes: 0,
                hours: 3,
                days: 0,
                price: "20,000 Gold",
            },  
            {
                name: 'Archer Tower Level 5',
                seconds: 0,
                minutes: 0,
                hours: 5,
                days: 0,
                price: "80,000 Gold",
            },  
            {
                name: 'Archer Tower Level 6',
                seconds: 0,
                minutes: 0,
                hours: 8,
                days: 0,
                price: "180,000 Gold",
            },  
            {
                name: 'Archer Tower Level 6',
                seconds: 0,
                minutes: 0,
                hours: 8,
                days: 0,
                price: "180,000 Gold",
            },  
            {
                name: 'Archer Tower Level 6',
                seconds: 0,
                minutes: 0,
                hours: 8,
                days: 0,
                price: "180,000 Gold",
            },  
            {
                name: 'Mortar Level 3',
                seconds: 0,
                minutes: 0,
                hours: 12,
                days: 0,
                price: "100,000 Gold",
            },
            {
                name: 'Air Defense Level 3',
                seconds: 0,
                minutes: 0,
                hours: 16,
                days: 0,
                price: "270,000 Gold",
            },
            {
                name: 'Wizard Tower (Build)',
                seconds: 0,
                minutes: 0,
                hours: 3,
                days: 0,
                price: "120,000 Gold",
            },
            {
                name: 'Wizard Tower Level 2',
                seconds: 0,
                minutes: 0,
                hours: 8,
                days: 0,
                price: "220,000 Gold",
            },
            ],
            THLVL6: [
            {
                name: 'Cannon Level 7',
                seconds: 0,
                minutes: 0,
                hours: 8,
                days: 0,
                price: "200,000 Gold",
            },
            {
                name: 'Cannon Level 7',
                seconds: 0,
                minutes: 0,
                hours: 8,
                days: 0,
                price: "200,000 Gold",
            },
            {
                name: 'Cannon Level 7',
                seconds: 0,
                minutes: 0,
                hours: 8,
                days: 0,
                price: "200,000 Gold",
            },
            {
                name: 'Archer Tower Level 7',
                seconds: 0,
                minutes: 0,
                hours: 10,
                days: 0,
                price: "360,000 Gold",
            },  
            {
                name: 'Archer Tower Level 7',
                seconds: 0,
                minutes: 0,
                hours: 10,
                days: 0,
                price: "360,000 Gold",
            },  
            {
                name: 'Archer Tower Level 7',
                seconds: 0,
                minutes: 0,
                hours: 10,
                days: 0,
                price: "360,000 Gold",
            },  
            {
                name: 'Mortar (Build)',
                seconds: 0,
                minutes: 0,
                hours: 3,
                days: 0,
                price: "5,000 Gold",
            },
            {
                name: 'Mortar Level 2',
                seconds: 0,
                minutes: 0,
                hours: 6,
                days: 0,
                price: "25,000 Gold",
            },
            {
                name: 'Mortar Level 3',
                seconds: 0,
                minutes: 0,
                hours: 12,
                days: 0,
                price: "100,000 Gold",
            },
            {
                name: 'Mortar Level 4',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 1,
                price: "200,000 Gold",
            },
            {
                name: 'Mortar Level 4',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 1,
                price: "200,000 Gold",
            },
            {
                name: 'Air Defense (Build)',
                seconds: 0,
                minutes: 0,
                hours: 3,
                days: 0,
                price: "22,000 Gold",
            },
            {
                name: 'Air Defense Level 2',
                seconds: 0,
                minutes: 0,
                hours: 12,
                days: 0,
                price: "90,000 Gold",
            },
            {
                name: 'Air Defense Level 3',
                seconds: 0,
                minutes: 0,
                hours: 16,
                days: 0,
                price: "270,000 Gold",
            },
            {
                name: 'Air Defense Level 4',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 1,
                price: "500,000 Gold",
            },
            {
                name: 'Air Defense Level 4',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 1,
                price: "500,000 Gold",
            },
            {
                name: 'Wizard Tower (Build)',
                seconds: 0,
                minutes: 0,
                hours: 3,
                days: 0,
                price: "120,000 Gold",
            },
            {
                name: 'Wizard Tower Level 2',
                seconds: 0,
                minutes: 0,
                hours: 8,
                days: 0,
                price: "220,000 Gold",
            },
            {
                name: 'Wizard Tower Level 3',
                seconds: 0,
                minutes: 0,
                hours: 12,
                days: 0,
                price: "420,000 Gold",
            },
            {
                name: 'Wizard Tower Level 3',
                seconds: 0,
                minutes: 0,
                hours: 12,
                days: 0,
                price: "420,000 Gold",
            },
            ],
            THLVL7: [
            {
                name: 'Cannon (Build) #4',
                seconds: 10,
                minutes: 0,
                hours: 0,
                days: 0,
                price: "250 Gold",
            },
            {
                name: 'Cannon (Build) #5',
                seconds: 10,
                minutes: 0,
                hours: 0,
                days: 0,
                price: "250 Gold",
            },
            {
                name: 'Cannon Level 2 #4',
                seconds: 0,
                minutes: 2,
                hours: 0,
                days: 0,
                price: "1,000 Gold",
            },
            {
                name: 'Cannon Level 2 #5',
                seconds: 0,
                minutes: 2,
                hours: 0,
                days: 0,
                price: "1,000 Gold",
            },
            {
                name: 'Cannon Level 3 #4',
                seconds: 0,
                minutes: 10,
                hours: 0,
                days: 0,
                price: "4,000 Gold",
            },
            {
                name: 'Cannon Level 3 #5',
                seconds: 0,
                minutes: 10,
                hours: 0,
                days: 0,
                price: "4,000 Gold",
            },
            {
                name: 'Cannon Level 4 #4',
                seconds: 0,
                minutes: 45,
                hours: 0,
                days: 0,
                price: "16,000 Gold",
            },
            {
                name: 'Cannon Level 4 #5',
                seconds: 0,
                minutes: 45,
                hours: 0,
                days: 0,
                price: "16,000 Gold",
            },
            {
                name: 'Cannon Level 5 #4',
                seconds: 0,
                minutes: 0,
                hours: 2,
                days: 0,
                price: "16,000 Gold",
            },
            {
                name: 'Cannon Level 5 #5',
                seconds: 0,
                minutes: 0,
                hours: 2,
                days: 0,
                price: "16,000 Gold",
            },
            {
                name: 'Cannon Level 6 #4',
                seconds: 0,
                minutes: 0,
                hours: 4,
                days: 0,
                price: "100,000 Gold",
            },
            {
                name: 'Cannon Level 6 #5',
                seconds: 0,
                minutes: 0,
                hours: 4,
                days: 0,
                price: "100,000 Gold",
            },
            {
                name: 'Cannon Level 7 #4',
                seconds: 0,
                minutes: 0,
                hours: 8,
                days: 0,
                price: "200,000 Gold",
            },
            {
                name: 'Cannon Level 7 #5',
                seconds: 0,
                minutes: 0,
                hours: 8,
                days: 0,
                price: "200,000 Gold",
            },
            {
                name: 'Cannon Level 8 #1',
                seconds: 0,
                minutes: 0,
                hours: 10,
                days: 0,
                price: "300,000 Gold",
            },
            {
                name: 'Cannon Level 8 #2',
                seconds: 0,
                minutes: 0,
                hours: 10,
                days: 0,
                price: "300,000 Gold",
            },
            {
                name: 'Cannon Level 8 #3',
                seconds: 0,
                minutes: 0,
                hours: 10,
                days: 0,
                price: "300,000 Gold",
            },
            {
                name: 'Cannon Level 8 #4',
                seconds: 0,
                minutes: 0,
                hours: 10,
                days: 0,
                price: "300,000 Gold",
            },
            {
                name: 'Cannon Level 8 #5',
                seconds: 0,
                minutes: 0,
                hours: 10,
                days: 0,
                price: "300,000 Gold",
            },
            {
                name: 'Archer Tower (Build)',
                seconds: 0,
                minutes: 1,
                hours: 0,
                days: 0,
                price: "1,000 Gold",
            },  
            {
                name: 'Archer Tower Level 2',
                seconds: 0,
                minutes: 15,
                hours: 0,
                days: 0,
                price: "2,000 Gold",
            }, 
            {
                name: 'Archer Tower Level 3',
                seconds: 0,
                minutes: 45,
                hours: 0,
                days: 0,
                price: "5,000 Gold",
            }, 
            {
                name: 'Archer Tower Level 4',
                seconds: 0,
                minutes: 0,
                hours: 3,
                days: 0,
                price: "20,000 Gold",
            },  
            {
                name: 'Archer Tower Level 5',
                seconds: 0,
                minutes: 0,
                hours: 5,
                days: 0,
                price: "80,000 Gold",
            },  
            {
                name: 'Archer Tower Level 6',
                seconds: 0,
                minutes: 0,
                hours: 8,
                days: 0,
                price: "180,000 Gold",
            },
            {
                name: 'Archer Tower Level 7',
                seconds: 0,
                minutes: 0,
                hours: 10,
                days: 0,
                price: "180,000 Gold",
            },
            {
                name: 'Archer Tower Level 7',
                seconds: 0,
                minutes: 0,
                hours: 10,
                days: 0,
                price: "180,000 Gold",
            },
            {
                name: 'Archer Tower Level 7',
                seconds: 0,
                minutes: 0,
                hours: 10,
                days: 0,
                price: "180,000 Gold",
            },
            {
                name: 'Archer Tower Level 7',
                seconds: 0,
                minutes: 0,
                hours: 10,
                days: 0,
                price: "180,000 Gold",
            },
            {
                name: 'Mortar (Build)',
                seconds: 0,
                minutes: 0,
                hours: 3,
                days: 0,
                price: "5,000 Gold",
            },
            {
                name: 'Mortar Level 2',
                seconds: 0,
                minutes: 0,
                hours: 6,
                days: 0,
                price: "25,000 Gold",
            },
            {
                name: 'Mortar Level 3',
                seconds: 0,
                minutes: 0,
                hours: 12,
                days: 0,
                price: "100,000 Gold",
            },
            {
                name: 'Mortar Level 4',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 1,
                price: "200,000 Gold",
            },
            {
                name: 'Mortar Level 5',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 2,
                price: "400,000 Gold",
            },
            {
                name: 'Mortar Level 5',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 2,
                price: "400,000 Gold",
            },
            {
                name: 'Mortar Level 5',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 2,
                price: "400,000 Gold",
            },
            {
                name: 'Air Defense (Build)',
                seconds: 0,
                minutes: 0,
                hours: 3,
                days: 0,
                price: "22,000 Gold",
            },
            {
                name: 'Air Defense Level 2',
                seconds: 0,
                minutes: 0,
                hours: 12,
                days: 0,
                price: "90,000 Gold",
            },
            {
                name: 'Air Defense Level 3',
                seconds: 0,
                minutes: 0,
                hours: 16,
                days: 0,
                price: "270,000 Gold",
            },
            {
                name: 'Air Defense Level 4',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 1,
                price: "500,000 Gold",
            },
            {
                name: 'Air Defense Level 4',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 1,
                price: "500,000 Gold",
            },
            {
                name: 'Air Defense Level 5',
                seconds: 0,
                minutes: 0,
                hours: 12,
                days: 1,
                price: "1,000,000 Gold",
            },
            {
                name: 'Air Defense Level 5',
                seconds: 0,
                minutes: 0,
                hours: 12,
                days: 1,
                price: "1,000,000 Gold",
            },
            {
                name: 'Air Defense Level 5',
                seconds: 0,
                minutes: 0,
                hours: 12,
                days: 1,
                price: "1,000,000 Gold",
            },
            {
                name: 'Wizard Tower Level 4',
                seconds: 0,
                minutes: 0,
                hours: 18,
                days: 0,
                price: "720,000 Gold",
            },
            {
                name: 'Wizard Tower Level 4',
                seconds: 0,
                minutes: 0,
                hours: 18,
                days: 0,
                price: "720,000 Gold",
            },
            ],
            THLVL8: [],
            THLVL9: [
            {
                name: 'Cannon Level 11 #1 ',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 1,
                price: "1,000,000 Gold",
            },
            {
                name: 'Cannon Level 11 #2 ',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 1,
                price: "1,000,000 Gold",
            },
            {
                name: 'Cannon Level 11 #3 ',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 1,
                price: "1,000,000 Gold",
            },
            {
                name: 'Cannon Level 11 #4 ',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 1,
                price: "1,000,000 Gold",
            },
            {
                name: 'Cannon Level 11 #5 ',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 1,
                price: "1,000,000 Gold",
            },
            {
                name: 'Archer Tower (Build) #6',
                seconds: 0,
                minutes: 1,
                hours: 0,
                days: 0,
                price: "1,000 Gold",
            },  
            {
                name: 'Archer Tower Level 2 #6',
                seconds: 0,
                minutes: 15,
                hours: 0,
                days: 0,
                price: "2,000 Gold",
            }, 
            {
                name: 'Archer Tower Level 3 #6',
                seconds: 0,
                minutes: 45,
                hours: 0,
                days: 0,
                price: "5,000 Gold",
            }, 
            {
                name: 'Archer Tower Level 4 #6',
                seconds: 0,
                minutes: 0,
                hours: 3,
                days: 0,
                price: "20,000 Gold",
            },  
            {
                name: 'Archer Tower Level 5 #6',
                seconds: 0,
                minutes: 0,
                hours: 5,
                days: 0,
                price: "80,000 Gold",
            },  
            {
                name: 'Archer Tower Level 6 #6',
                seconds: 0,
                minutes: 0,
                hours: 8,
                days: 0,
                price: "180,000 Gold",
            },
            {
                name: 'Archer Tower Level 7 #6',
                seconds: 0,
                minutes: 0,
                hours: 10,
                days: 0,
                price: "360,000 Gold",
            },
            {
                name: 'Archer Tower Level 8 #6',
                seconds: 0,
                minutes: 0,
                hours: 12,
                days: 0,
                price: "600,000 Gold",
            },
            {
                name: 'Archer Tower Level 9 #6',
                seconds: 0,
                minutes: 0,
                hours: 14,
                days: 0,
                price: "800,000 Gold",
            },
            {
                name: 'Archer Tower Level 10 #6',
                seconds: 0,
                minutes: 0,
                hours: 18,
                days: 0,
                price: "1,000,000 Gold",
            },
            {
                name: 'Archer Tower Level 11 #1',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 1,
                price: "1,200,000 Gold",
            },
            {
                name: 'Archer Tower Level 11 #2',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 1,
                price: "1,200,000 Gold",
            },
            {
                name: 'Archer Tower Level 11 #3',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 1,
                price: "1,200,000 Gold",
            },
            {
                name: 'Archer Tower Level 11 #4',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 1,
                price: "1,200,000 Gold",
            },
            {
                name: 'Archer Tower Level 11 #5',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 1,
                price: "1,200,000 Gold",
            },
            {
                name: 'Archer Tower Level 11 #6',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 1,
                price: "1,200,000 Gold",
            },
            {
                name: 'Mortar Level 7 #1',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 3,
                price: "1,500,000 Gold",
            },
            {
                name: 'Mortar Level 7 #2',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 3,
                price: "1,500,000 Gold",
            },
            {
                name: 'Mortar Level 7 #3',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 3,
                price: "1,500,000 Gold",
            },
            {
                name: 'Mortar Level 7 #4',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 3,
                price: "1,500,000 Gold",
            },
            {
                name: 'Air Defense (Build) #4',
                seconds: 0,
                minutes: 0,
                hours: 3,
                days: 0,
                price: "22,000 Gold",
            },
            {
                name: 'Air Defense Level 2 #4',
                seconds: 0,
                minutes: 0,
                hours: 12,
                days: 0,
                price: "90,000 Gold",
            },
            {
                name: 'Air Defense Level 3 #4',
                seconds: 0,
                minutes: 0,
                hours: 16,
                days: 0,
                price: "270,000 Gold",
            },
            {
                name: 'Air Defense Level 4 #4',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 1,
                price: "500,000 Gold",
            },
            {
                name: 'Air Defense Level 5 #4',
                seconds: 0,
                minutes: 0,
                hours: 12,
                days: 1,
                price: "1,000,000 Gold",
            },
            {
                name: 'Air Defense Level 6 #4',
                seconds: 0,
                minutes: 0,
                hours: 12,
                days: 1,
                price: "1,350,000 Gold",
            },
            {
                name: 'Air Defense Level 7 #1',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 3,
                price: "1,750,000 Gold",
            },
            {
                name: 'Air Defense Level 7 #2',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 3,
                price: "1,750,000 Gold",
            },
            {
                name: 'Air Defense Level 7 #3',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 3,
                price: "1,750,000 Gold",
            },
            {
                name: 'Air Defense Level 7 #4',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 3,
                price: "1,750,000 Gold",
            },
            {
                name: 'Wizard Tower (Build)) #4',
                seconds: 0,
                minutes: 0,
                hours: 3,
                days: 0,
                price: "120,000 Gold",
            },
            {
                name: 'Wizard Tower Level 2 #4',
                seconds: 0,
                minutes: 0,
                hours: 8,
                days: 0,
                price: "220,000 Gold",
            },
            {
                name: 'Wizard Tower Level 3 #4',
                seconds: 0,
                minutes: 0,
                hours: 12,
                days: 0,
                price: "420,000 Gold",
            },
            {
                name: 'Wizard Tower Level 4 #4',
                seconds: 0,
                minutes: 0,
                hours: 18,
                days: 0,
                price: "720,000 Gold",
            },
            {
                name: 'Wizard Tower Level 5 #4',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 1,
                price: "920,000 Gold",
            },
            {
                name: 'Wizard Tower Level 6 #4',
                seconds: 0,
                minutes: 0,
                hours: 12,
                days: 1,
                price: "1,200,000 Gold",
            },
            {
                name: 'Wizard Tower Level 7 #1',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 2,
                price: "2,200,000 Gold",
            },
            {
                name: 'Wizard Tower Level 7 #2',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 2,
                price: "2,200,000 Gold",
            },
            {
                name: 'Wizard Tower Level 7 #3',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 2,
                price: "2,200,000 Gold",
            },
            {
                name: 'Wizard Tower Level 7 #4',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 2,
                price: "2,200,000 Gold",
            },
            {
                name: 'Air Sweeper (Build) #1',
                seconds: 0,
                minutes: 0,
                hours: 6,
                days: 0,
                price: "400,000 Gold",
            },
            {
                name: 'Air Sweeper Level 2 #1',
                seconds: 0,
                minutes: 0,
                hours: 12,
                days: 0,
                price: "700,000 Gold",
            },
            {
                name: 'Air Sweeper Level 3 #1',
                seconds: 0,
                minutes: 0,
                hours: 18,
                days: 0,
                price: "1,100,000 Gold",
            },
            {
                name: 'Air Sweeper Level 4 #1',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 1,
                price: "1,500,000 Gold",
            },
            {
                name: 'Air Sweeper Level 5 #2',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 2,
                price: "2,000,000 Gold",
            },
            {
                name: 'Air Sweeper Level 5 #2',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 2,
                price: "2,000,000 Gold",
            },
            {
                name: 'Hidden Tesla (Build) #4',
                seconds: 0,
                minutes: 0,
                hours: 2,
                days: 0,
                price: "300,000 Gold",
            },
            {
                name: 'Hidden Tesla Level 2 #4',
                seconds: 0,
                minutes: 0,
                hours: 5,
                days: 0,
                price: "450,000 Gold",
            },
            {
                name: 'Hidden Tesla Level 3 #4',
                seconds: 0,
                minutes: 0,
                hours: 10,
                days: 0,
                price: "650,000 Gold",
            },
            {
                name: 'Hidden Tesla Level 4 #4',
                seconds: 0,
                minutes: 0,
                hours: 18,
                days: 0,
                price: "850,000 Gold",
            },
            {
                name: 'Hidden Tesla Level 5 #4',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 1,
                price: "1,100,000 Gold",
            },
            {
                name: 'Hidden Tesla Level 6 #4',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 2,
                price: "1,300,000 Gold",
            },
            {
                name: 'Hidden Tesla Level 7 #4',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 3,
                price: "1,800,000 Gold",
            },
            {
                name: 'Hidden Tesla Level 7 #1',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 3,
                price: "1,800,000 Gold",
            },
            {
                name: 'Hidden Tesla Level 7 #2',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 3,
                price: "1,800,000 Gold",
            },
            {
                name: 'Hidden Tesla Level 7 #3',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 3,
                price: "1,800,000 Gold",
            },
            {
                name: 'Bomb Tower 3 #1',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 2,
                price: "1,800,000 Gold",
            },
            {
                name: 'X-Bow (Build) #1',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 2,
                price: "1,000,000 Gold",
            },
            {
                name: 'X-Bow (Build) #2',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 2,
                price: "1,000,000 Gold",
            },
            {
                name: 'X-Bow Level 2 #1',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 4,
                price: "1,600,000 Gold",
            },
            {
                name: 'X-Bow Level 2 #2',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 4,
                price: "1,600,000 Gold",
            },
            {
                name: 'X-Bow Level 3 #1',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 5,
                price: "2,400,000 Gold",
            },
            {
                name: 'X-Bow Level 3 #2',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 5,
                price: "2,400,000 Gold",
            },
            ],
            THLVL10: [],
            THLVL11: [],
            THLVL12: [],
            THLVL13: [],
            THLVL14: [],
        THLVL15: [
          {
            name: 'Cannon',
            hours: 100,
            days: 5,
          },
          {
            name: 'Archer Tower',
            hours: 100,
            days: 5,
          },
          {
          name: 'Mortar',
          hours: 1,
          days: 1,
        },
        {
          name: 'Air Defense',
          hours: 1,
          days: 1,
        },
        {
          name: 'Wizard Tower',
          hours: 1,
          days: 1,
        },
        {
          name: 'Air Sweeper',
          hours: 1,
          days: 1,
        },
        {
          name: 'Hidden Tesla',
          hours: 1,
          days: 1,
        },
        {
          name: 'Bomb Tower',
          hours: 1,
          days: 1,
        },
        {
          name: 'X-Bow',
          hours: 1,
          days: 1,
        },
        {
          name: 'Inferno Tower',
          hours: 1,
          days: 1,
        },
        {
          name: 'Eagle Artillery',
          hours: 1,
          days: 1,
        },
        {
          name: 'Scattershot',
          hours: 1,
          days: 1,
        },
        {
          name: "Builder's Hut",
          hours: 1,
          days: 1,
        },
        {
          name: 'Spell Tower',
          hours: 1,
          days: 1,
        },
        {
          name: 'Monolith',
          hours: 1,
          days: 1,
        },
        ],
      },
    };
    },
        computed: {
            currentDefensiveBuildings() {
                return this.DefensiveBuildings[`THLVL${this.THLevelMenu.slice(2)}`] || [];
            },
        },
        methods: {
            toggleTableVisibility() {
                this.showDefensiveBuildingsTable = !this.showDefensiveBuildingsTable;
                this.$emit('timerUpdatedDefensiveBuildings', this.getTimer());
            },
            
            sumProperty(propertyName) {
                return this.currentDefensiveBuildings.reduce((total, DefensiveBuilding) => total + DefensiveBuilding[propertyName], 0);
            },
        
            getTimer() {
                let totalSeconds = this.sumProperty('seconds') + this.sumProperty('minutes') * 60 + this.sumProperty('hours') * 3600 + this.sumProperty('days') * 86400;
                
                const days = Math.floor(totalSeconds / 86400);
                totalSeconds -= days * 86400;
                
                const hours = Math.floor(totalSeconds / 3600);
                totalSeconds -= hours * 3600;
                
                const minutes = Math.floor(totalSeconds / 60);
                const seconds = totalSeconds % 60;
            
                const timer = `${days} Days ${hours} Hours ${minutes} Minutes ${seconds} Seconds`;

                this.$emit('timerUpdatedDefensiveBuildings', timer);

                return timer;
            },
        },
        mounted() {
            this.getTimer();
            const timerInterval  = setInterval(() => {
                this.getTimer();
            }, 1000);
        },
        beforeDestroy() {
            clearInterval(timerInterval);
        },
    }
</script>

<style scoped>

</style>