<template>
    <div>
      <v-card>
        <v-card-item>
          <v-card-title>
            <select v-model="THLevelMenu">
                <option v-for="level in THLevels" :key="level">{{ `TH${level}` }}</option>
            </select>
          </v-card-title>
          <v-card-text>
            <p style="font-weight: 700; font-size: x-large;" class="my-5">Defensive Buildings</p>
            <v-table>
              <thead>
                <tr>
                  <th class="text-left" style="font-weight: 700; color: #000;">Name</th>
                  <th class="text-left" style="font-weight: 700; color: #000;">Seconds</th>
                  <th class="text-left" style="font-weight: 700; color: #000;">Minutes</th>
                  <th class="text-left" style="font-weight: 700; color: #000;">Hours</th>
                  <th class="text-left" style="font-weight: 700; color: #000;">Days</th>
                  <th class="text-left" style="font-weight: 700; color: #000;">Price</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="defensiveBuilding in currentDefensiveBuildings" :key="defensiveBuilding.name">
                    <td>{{ defensiveBuilding.name }}</td>
                    <td>{{ defensiveBuilding.seconds }}</td>
                    <td>{{ defensiveBuilding.minutes }}</td>
                    <td>{{ defensiveBuilding.hours }}</td>
                    <td>{{ defensiveBuilding.days }}</td>
                    <td>{{ defensiveBuilding.price }}</td>
                </tr>
              </tbody>
            </v-table>
          </v-card-text>
        </v-card-item>
      </v-card>
    </div>
</template>
  
<script>
export default {
  data() {
    return {
      THLevelMenu: 'TH1',
      THLevels: Array.from({ length: 15 }, (_, i) => i + 1),
      DefensiveBuildings: {
            THLVL1: [
            {
                name: 'Cannon (Build)',
                seconds: 10,
                minutes: 0,
                hours: 0,
                days: 0,
                price: "250 Gold",
            },
            {
                name: 'Cannon (Build)',
                seconds: 10,
                minutes: 0,
                hours: 0,
                days: 0,
                price: "250 Gold",
            },
            {
                name: 'Cannon Level 2',
                seconds: 0,
                minutes: 2,
                hours: 0,
                days: 0,
                price: "1,000 Gold",
            },
            {
                name: 'Cannon Level 2',
                seconds: 0,
                minutes: 2,
                hours: 0,
                days: 0,
                price: "1,000 Gold",
            },
            ],
            THLVL2: [
            {
                name: 'Cannon Level 3',
                seconds: 0,
                minutes: 10,
                hours: 0,
                days: 0,
                price: "4,000 Gold",
            },
            {
                name: 'Cannon Level 3',
                seconds: 0,
                minutes: 10,
                hours: 0,
                days: 0,
                price: "4,000 Gold",
            },
            {
                name: 'Archer Tower (Build)',
                seconds: 0,
                minutes: 1,
                hours: 0,
                days: 0,
                price: "1,000 Gold",
            },  
            {
                name: 'Archer Tower Level 2',
                seconds: 0,
                minutes: 15,
                hours: 0,
                days: 0,
                price: "2,000 Gold",
            },  
            ],
            THLVL3: [
            {
                name: 'Cannon Level 4',
                seconds: 0,
                minutes: 45,
                hours: 0,
                days: 0,
                price: "16,000 Gold",
            },
            {
                name: 'Cannon Level 4',
                seconds: 0,
                minutes: 45,
                hours: 0,
                days: 0,
                price: "16,000 Gold",
            },
            {
                name: 'Archer Tower Level 3',
                seconds: 0,
                minutes: 45,
                hours: 0,
                days: 0,
                price: "5,000 Gold",
            },  
            {
                name: 'Mortar (Build)',
                seconds: 0,
                minutes: 0,
                hours: 3,
                days: 0,
                price: "5,000 Gold",
            },
            ],
            THLVL4: [
            {
                name: 'Cannon Level 5',
                seconds: 0,
                minutes: 0,
                hours: 2,
                days: 0,
                price: "16,000 Gold",
            },
            {
                name: 'Cannon Level 5',
                seconds: 0,
                minutes: 0,
                hours: 2,
                days: 0,
                price: "16,000 Gold",
            },
            {
                name: 'Archer Tower (Build)',
                seconds: 0,
                minutes: 1,
                hours: 0,
                days: 0,
                price: "1,000 Gold",
            },  
            {
                name: 'Archer Tower Level 2',
                seconds: 0,
                minutes: 15,
                hours: 0,
                days: 0,
                price: "2,000 Gold",
            }, 
            {
                name: 'Archer Tower Level 3',
                seconds: 0,
                minutes: 45,
                hours: 0,
                days: 0,
                price: "5,000 Gold",
            },  
            {
                name: 'Archer Tower Level 4',
                seconds: 0,
                minutes: 0,
                hours: 3,
                days: 0,
                price: "20,000 Gold",
            },  
            {
                name: 'Archer Tower Level 4',
                seconds: 0,
                minutes: 0,
                hours: 3,
                days: 0,
                price: "20,000 Gold",
            },  
            {
                name: 'Mortar Level 2',
                seconds: 0,
                minutes: 0,
                hours: 6,
                days: 0,
                price: "25,000 Gold",
            },
            {
                name: 'Air Defense (Build)',
                seconds: 0,
                minutes: 0,
                hours: 3,
                days: 0,
                price: "22,000 Gold",
            },
            {
                name: 'Air Defense Level 2',
                seconds: 0,
                minutes: 0,
                hours: 12,
                days: 0,
                price: "90,000 Gold",
            },
            ],
            THLVL5: [
            {
                name: 'Cannon (Build)',
                seconds: 10,
                minutes: 0,
                hours: 0,
                days: 0,
                price: "250 Gold",
            },
            {
                name: 'Cannon Level 2',
                seconds: 0,
                minutes: 2,
                hours: 0,
                days: 0,
                price: "1,000 Gold",
            },
            {
                name: 'Cannon Level 3',
                seconds: 0,
                minutes: 10,
                hours: 0,
                days: 0,
                price: "4,000 Gold",
            },
            {
                name: 'Cannon Level 4',
                seconds: 0,
                minutes: 45,
                hours: 0,
                days: 0,
                price: "16,000 Gold",
            },
            {
                name: 'Cannon Level 5',
                seconds: 0,
                minutes: 0,
                hours: 2,
                days: 0,
                price: "16,000 Gold",
            },
            {
                name: 'Cannon Level 6',
                seconds: 0,
                minutes: 0,
                hours: 4,
                days: 0,
                price: "100,000 Gold",
            },
            {
                name: 'Cannon Level 6',
                seconds: 0,
                minutes: 0,
                hours: 4,
                days: 0,
                price: "100,000 Gold",
            },
            {
                name: 'Cannon Level 6',
                seconds: 0,
                minutes: 0,
                hours: 4,
                days: 0,
                price: "100,000 Gold",
            },
            {
                name: 'Archer Tower (Build)',
                seconds: 0,
                minutes: 1,
                hours: 0,
                days: 0,
                price: "1,000 Gold",
            },  
            {
                name: 'Archer Tower Level 2',
                seconds: 0,
                minutes: 15,
                hours: 0,
                days: 0,
                price: "2,000 Gold",
            }, 
            {
                name: 'Archer Tower Level 3',
                seconds: 0,
                minutes: 45,
                hours: 0,
                days: 0,
                price: "5,000 Gold",
            }, 
            {
                name: 'Archer Tower Level 4',
                seconds: 0,
                minutes: 0,
                hours: 3,
                days: 0,
                price: "20,000 Gold",
            },  
            {
                name: 'Archer Tower Level 5',
                seconds: 0,
                minutes: 0,
                hours: 5,
                days: 0,
                price: "80,000 Gold",
            },  
            {
                name: 'Archer Tower Level 6',
                seconds: 0,
                minutes: 0,
                hours: 8,
                days: 0,
                price: "180,000 Gold",
            },  
            {
                name: 'Archer Tower Level 6',
                seconds: 0,
                minutes: 0,
                hours: 8,
                days: 0,
                price: "180,000 Gold",
            },  
            {
                name: 'Archer Tower Level 6',
                seconds: 0,
                minutes: 0,
                hours: 8,
                days: 0,
                price: "180,000 Gold",
            },  
            {
                name: 'Mortar Level 3',
                seconds: 0,
                minutes: 0,
                hours: 12,
                days: 0,
                price: "100,000 Gold",
            },
            {
                name: 'Air Defense Level 3',
                seconds: 0,
                minutes: 0,
                hours: 16,
                days: 0,
                price: "270,000 Gold",
            },
            {
                name: 'Wizard Tower (Build)',
                seconds: 0,
                minutes: 0,
                hours: 3,
                days: 0,
                price: "120,000 Gold",
            },
            {
                name: 'Wizard Tower Level 2',
                seconds: 0,
                minutes: 0,
                hours: 8,
                days: 0,
                price: "220,000 Gold",
            },
            ],
            THLVL6: [
            {
                name: 'Cannon Level 7',
                seconds: 0,
                minutes: 0,
                hours: 8,
                days: 0,
                price: "200,000 Gold",
            },
            {
                name: 'Cannon Level 7',
                seconds: 0,
                minutes: 0,
                hours: 8,
                days: 0,
                price: "200,000 Gold",
            },
            {
                name: 'Cannon Level 7',
                seconds: 0,
                minutes: 0,
                hours: 8,
                days: 0,
                price: "200,000 Gold",
            },
            {
                name: 'Archer Tower Level 7',
                seconds: 0,
                minutes: 0,
                hours: 10,
                days: 0,
                price: "360,000 Gold",
            },  
            {
                name: 'Archer Tower Level 7',
                seconds: 0,
                minutes: 0,
                hours: 10,
                days: 0,
                price: "360,000 Gold",
            },  
            {
                name: 'Archer Tower Level 7',
                seconds: 0,
                minutes: 0,
                hours: 10,
                days: 0,
                price: "360,000 Gold",
            },  
            {
                name: 'Mortar (Build)',
                seconds: 0,
                minutes: 0,
                hours: 3,
                days: 0,
                price: "5,000 Gold",
            },
            {
                name: 'Mortar Level 2',
                seconds: 0,
                minutes: 0,
                hours: 6,
                days: 0,
                price: "25,000 Gold",
            },
            {
                name: 'Mortar Level 3',
                seconds: 0,
                minutes: 0,
                hours: 12,
                days: 0,
                price: "100,000 Gold",
            },
            {
                name: 'Mortar Level 4',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 1,
                price: "200,000 Gold",
            },
            {
                name: 'Mortar Level 4',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 1,
                price: "200,000 Gold",
            },
            {
                name: 'Air Defense (Build)',
                seconds: 0,
                minutes: 0,
                hours: 3,
                days: 0,
                price: "22,000 Gold",
            },
            {
                name: 'Air Defense Level 2',
                seconds: 0,
                minutes: 0,
                hours: 12,
                days: 0,
                price: "90,000 Gold",
            },
            {
                name: 'Air Defense Level 3',
                seconds: 0,
                minutes: 0,
                hours: 16,
                days: 0,
                price: "270,000 Gold",
            },
            {
                name: 'Air Defense Level 4',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 1,
                price: "500,000 Gold",
            },
            {
                name: 'Air Defense Level 4',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 1,
                price: "500,000 Gold",
            },
            {
                name: 'Wizard Tower (Build)',
                seconds: 0,
                minutes: 0,
                hours: 3,
                days: 0,
                price: "120,000 Gold",
            },
            {
                name: 'Wizard Tower Level 2',
                seconds: 0,
                minutes: 0,
                hours: 8,
                days: 0,
                price: "220,000 Gold",
            },
            {
                name: 'Wizard Tower Level 3',
                seconds: 0,
                minutes: 0,
                hours: 12,
                days: 0,
                price: "420,000 Gold",
            },
            {
                name: 'Wizard Tower Level 3',
                seconds: 0,
                minutes: 0,
                hours: 12,
                days: 0,
                price: "420,000 Gold",
            },
            ],
            THLVL7: [
            {
                name: 'Cannon (Build)',
                seconds: 10,
                minutes: 0,
                hours: 0,
                days: 0,
                price: "250 Gold",
            },
            {
                name: 'Cannon (Build)',
                seconds: 10,
                minutes: 0,
                hours: 0,
                days: 0,
                price: "250 Gold",
            },
            {
                name: 'Cannon Level 2',
                seconds: 0,
                minutes: 2,
                hours: 0,
                days: 0,
                price: "1,000 Gold",
            },
            {
                name: 'Cannon Level 2',
                seconds: 0,
                minutes: 2,
                hours: 0,
                days: 0,
                price: "1,000 Gold",
            },
            {
                name: 'Cannon Level 3',
                seconds: 0,
                minutes: 10,
                hours: 0,
                days: 0,
                price: "4,000 Gold",
            },
            {
                name: 'Cannon Level 3',
                seconds: 0,
                minutes: 10,
                hours: 0,
                days: 0,
                price: "4,000 Gold",
            },
            {
                name: 'Cannon Level 4',
                seconds: 0,
                minutes: 45,
                hours: 0,
                days: 0,
                price: "16,000 Gold",
            },
            {
                name: 'Cannon Level 4',
                seconds: 0,
                minutes: 45,
                hours: 0,
                days: 0,
                price: "16,000 Gold",
            },
            {
                name: 'Cannon Level 5',
                seconds: 0,
                minutes: 0,
                hours: 2,
                days: 0,
                price: "16,000 Gold",
            },
            {
                name: 'Cannon Level 5',
                seconds: 0,
                minutes: 0,
                hours: 2,
                days: 0,
                price: "16,000 Gold",
            },
            {
                name: 'Cannon Level 6',
                seconds: 0,
                minutes: 0,
                hours: 4,
                days: 0,
                price: "100,000 Gold",
            },
            {
                name: 'Cannon Level 6',
                seconds: 0,
                minutes: 0,
                hours: 4,
                days: 0,
                price: "100,000 Gold",
            },
            {
                name: 'Cannon Level 7',
                seconds: 0,
                minutes: 0,
                hours: 8,
                days: 0,
                price: "200,000 Gold",
            },
            {
                name: 'Cannon Level 7',
                seconds: 0,
                minutes: 0,
                hours: 8,
                days: 0,
                price: "200,000 Gold",
            },
            {
                name: 'Cannon Level 8',
                seconds: 0,
                minutes: 0,
                hours: 10,
                days: 0,
                price: "300,000 Gold",
            },
            {
                name: 'Cannon Level 8',
                seconds: 0,
                minutes: 0,
                hours: 10,
                days: 0,
                price: "300,000 Gold",
            },
            {
                name: 'Cannon Level 8',
                seconds: 0,
                minutes: 0,
                hours: 10,
                days: 0,
                price: "300,000 Gold",
            },
            {
                name: 'Cannon Level 8',
                seconds: 0,
                minutes: 0,
                hours: 10,
                days: 0,
                price: "300,000 Gold",
            },
            {
                name: 'Cannon Level 8',
                seconds: 0,
                minutes: 0,
                hours: 10,
                days: 0,
                price: "300,000 Gold",
            },
            {
                name: 'Archer Tower (Build)',
                seconds: 0,
                minutes: 1,
                hours: 0,
                days: 0,
                price: "1,000 Gold",
            },  
            {
                name: 'Archer Tower Level 2',
                seconds: 0,
                minutes: 15,
                hours: 0,
                days: 0,
                price: "2,000 Gold",
            }, 
            {
                name: 'Archer Tower Level 3',
                seconds: 0,
                minutes: 45,
                hours: 0,
                days: 0,
                price: "5,000 Gold",
            }, 
            {
                name: 'Archer Tower Level 4',
                seconds: 0,
                minutes: 0,
                hours: 3,
                days: 0,
                price: "20,000 Gold",
            },  
            {
                name: 'Archer Tower Level 5',
                seconds: 0,
                minutes: 0,
                hours: 5,
                days: 0,
                price: "80,000 Gold",
            },  
            {
                name: 'Archer Tower Level 6',
                seconds: 0,
                minutes: 0,
                hours: 8,
                days: 0,
                price: "180,000 Gold",
            },
            {
                name: 'Archer Tower Level 7',
                seconds: 0,
                minutes: 0,
                hours: 10,
                days: 0,
                price: "180,000 Gold",
            },
            {
                name: 'Archer Tower Level 7',
                seconds: 0,
                minutes: 0,
                hours: 10,
                days: 0,
                price: "180,000 Gold",
            },
            {
                name: 'Archer Tower Level 7',
                seconds: 0,
                minutes: 0,
                hours: 10,
                days: 0,
                price: "180,000 Gold",
            },
            {
                name: 'Archer Tower Level 7',
                seconds: 0,
                minutes: 0,
                hours: 10,
                days: 0,
                price: "180,000 Gold",
            },
            {
                name: 'Mortar (Build)',
                seconds: 0,
                minutes: 0,
                hours: 3,
                days: 0,
                price: "5,000 Gold",
            },
            {
                name: 'Mortar Level 2',
                seconds: 0,
                minutes: 0,
                hours: 6,
                days: 0,
                price: "25,000 Gold",
            },
            {
                name: 'Mortar Level 3',
                seconds: 0,
                minutes: 0,
                hours: 12,
                days: 0,
                price: "100,000 Gold",
            },
            {
                name: 'Mortar Level 4',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 1,
                price: "200,000 Gold",
            },
            {
                name: 'Mortar Level 5',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 2,
                price: "400,000 Gold",
            },
            {
                name: 'Mortar Level 5',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 2,
                price: "400,000 Gold",
            },
            {
                name: 'Mortar Level 5',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 2,
                price: "400,000 Gold",
            },
            {
                name: 'Air Defense (Build)',
                seconds: 0,
                minutes: 0,
                hours: 3,
                days: 0,
                price: "22,000 Gold",
            },
            {
                name: 'Air Defense Level 2',
                seconds: 0,
                minutes: 0,
                hours: 12,
                days: 0,
                price: "90,000 Gold",
            },
            {
                name: 'Air Defense Level 3',
                seconds: 0,
                minutes: 0,
                hours: 16,
                days: 0,
                price: "270,000 Gold",
            },
            {
                name: 'Air Defense Level 4',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 1,
                price: "500,000 Gold",
            },
            {
                name: 'Air Defense Level 4',
                seconds: 0,
                minutes: 0,
                hours: 0,
                days: 1,
                price: "500,000 Gold",
            },
            {
                name: 'Air Defense Level 5',
                seconds: 0,
                minutes: 0,
                hours: 12,
                days: 1,
                price: "1,000,000 Gold",
            },
            {
                name: 'Air Defense Level 5',
                seconds: 0,
                minutes: 0,
                hours: 12,
                days: 1,
                price: "1,000,000 Gold",
            },
            {
                name: 'Air Defense Level 5',
                seconds: 0,
                minutes: 0,
                hours: 12,
                days: 1,
                price: "1,000,000 Gold",
            },
            {
                name: 'Wizard Tower Level 4',
                seconds: 0,
                minutes: 0,
                hours: 18,
                days: 0,
                price: "720,000 Gold",
            },
            {
                name: 'Wizard Tower Level 4',
                seconds: 0,
                minutes: 0,
                hours: 18,
                days: 0,
                price: "720,000 Gold",
            },
            ],
            THLVL8: [],
            THLVL9: [],
            THLVL10: [],
            THLVL11: [],
            THLVL12: [],
            THLVL13: [],
            THLVL14: [],
        THLVL15: [
          {
            name: 'Cannon',
            hours: 100,
            days: 5,
          },
          {
            name: 'Archer Tower',
            hours: 100,
            days: 5,
          },
          {
          name: 'Mortar',
          hours: 1,
          days: 1,
        },
        {
          name: 'Air Defense',
          hours: 1,
          days: 1,
        },
        {
          name: 'Wizard Tower',
          hours: 1,
          days: 1,
        },
        {
          name: 'Air Sweeper',
          hours: 1,
          days: 1,
        },
        {
          name: 'Hidden Tesla',
          hours: 1,
          days: 1,
        },
        {
          name: 'Bomb Tower',
          hours: 1,
          days: 1,
        },
        {
          name: 'X-Bow',
          hours: 1,
          days: 1,
        },
        {
          name: 'Inferno Tower',
          hours: 1,
          days: 1,
        },
        {
          name: 'Eagle Artillery',
          hours: 1,
          days: 1,
        },
        {
          name: 'Scattershot',
          hours: 1,
          days: 1,
        },
        {
          name: "Builder's Hut",
          hours: 1,
          days: 1,
        },
        {
          name: 'Spell Tower',
          hours: 1,
          days: 1,
        },
        {
          name: 'Monolith',
          hours: 1,
          days: 1,
        },
        ],
      },
      ResourcesBuildings: {
        THLVL1: [
            {
                name: 'Elixir Collector',
                hours: 0,
                days: 0,
                amount: 0,
                toLevel: 0,
                price: 0,
            },
            {
                name: 'Elixir Storage',
                hours: 0,
                days: 0,
                amount: 0,
                toLevel: 0,
                price: 0,
            },  
            {
                name: 'Gold Mine',
                hours: 0,
                days: 0,
                amount: 0,
                toLevel: 0,
                price: 0,
            },
            {
                name: 'Gold Storage',
                hours: 0,
                days: 0,
                amount: 0,
                toLevel: 0,
                price: 0,
            },
        ],
      },
      ArmyBuildings: {
        THLVL1: [
            {
                name: 'Army Camp',
                hours: 0,
                days: 0,
                amount: 0,
                toLevel: 0,
                price: 0,
            },
            {
                name: 'Barracks',
                hours: 0,
                days: 0,
                amount: 0,
                toLevel: 0,
                price: 0,
            },
        ],
      },
    };
  },
  computed: {
    currentDefensiveBuildings() {
      return this.DefensiveBuildings[`THLVL${this.THLevelMenu.slice(2)}`] || [];
    },
  },
};
</script>


<style scoped>

</style>